# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HistoriqueParcelle
                                 A QGIS plugin
 Historique des parcelles (cadastre français)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-09-04
        copyright            : (C) 2024 by HistoriqueParcelle.fr
        email                : contact@historiqueparcelle.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'HistoriqueParcelle.fr'
__date__ = '2024-09-04'
__copyright__ = '(C) 2024 by HistoriqueParcelle.fr'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HistoriqueParcelle class from file HistoriqueParcelle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Historique_Parcelle import HistoriqueParcellePlugin
    return HistoriqueParcellePlugin()
